---
title: "DATA 607 - Project 1"
author: "Jose Mawyin"
date: "9/11/2019"
output: pdf_document
---

```{r}
library(magrittr)

raw_data1 <- read.delim("https://raw.githubusercontent.com/JMawyin/MSDS2019/master/tournamentinfo.txt", header = TRUE, skip = 1, sep = "|", stringsAsFactors = FALSE)
head(raw_data1,4)
raw_data2 <- subset(raw_data1, Pair != "-----------------------------------------------------------------------------------------")
head(raw_data2,4)

raw.array.dimension <- dim(raw_data2)
endrow <- raw.array.dimension[1:1]
prune1 <- raw_data2[2:endrow, 1:10]
head(prune1,4)


```

```{r}
#Splitting cleaned data  into two frames each of 64 rows. Each row contains
#different bits of player information.
Odd.Row <- prune1[ c(TRUE,FALSE), ] 
Even.Row <- prune1[!c(TRUE,FALSE), ]

head(Odd.Row,5) ;head(Even.Row,5)
```


```{r}
#Code below separate the Player’s Pre-Rating information from a string mixing
#integers and character.
even.prune <- t(as.data.frame(strsplit(as.character(Even.Row$Player.Name), "\\->")))  
row.names(even.prune) <- c()

even.prune2 <- t(as.data.frame(strsplit(as.character(even.prune[,1]), " / R: ")))   
row.names(even.prune2) <- c()

Even.prune3 <- t(as.data.frame(strsplit(as.character(even.prune2[,2]), "P")))   
row.names(Even.prune3) <- c()
head(Even.prune3,5)  

Pre.Rating <- as.data.frame(as.numeric(trimws(Even.prune3[,1])))
```



```{r}
#Code below separate players Total Number of Points and the opponents ID for each
#of the 7 games played
Odd.prune <- as.data.frame(lapply(Odd.Row[.4:11], function(x) as.numeric(gsub("[a-zA-Z ]", "", x))))
row.names(Odd.prune) <- c()
head(Odd.prune,5)
#dim(test4)

```
```{r}
##Joining columns to form a new data frame contaning all the information of
#interest for us.

united <- as.data.frame(cbind(Odd.Row$Player.Name, Even.Row$Pair, Odd.prune$Total, Pre.Rating, Odd.prune[,4:10]))
colnames(united) <- c("Name", "State", "Total Points", "Pre-Rating", "Oppo1", "Oppo2", "Oppo3", "Oppo4", "Oppo5", "Oppo6","Oppo7")
head(united,4)

write.csv(united, file = "/Users/josemawyin/Library/Mobile Documents/com~apple~CloudDocs/Data Science Masters /607/Project1/UnitedScores.csv")
```



```{r}

Average.Rating <- 0

Average.Rating <- c(united[as.integer(united[1,5]),4] , united[as.integer(united[1,6]),4], united[as.integer(united[1,7]),4], united[as.integer(united[1,8]),4], united[as.integer(united[1,9]),4], united[as.integer(united[1,10]),4], united[as.integer(united[1,11]),4] ) %>% mean()
str(Average.Rating)

```

```{r}
Average.Rating <- c()

for(i in 1:64) {
Average.Rating <- rbind(Average.Rating, mean( c(united[as.integer(united[i,5]),4] , united[as.integer(united[i,6]),4], united[as.integer(united[i,7]),4], united[as.integer(united[i,8]),4], united[as.integer(united[i,9]),4], united[as.integer(united[i,10]),4], united[as.integer(united[i,11]),4] ),na.rm=TRUE))
}
head(Average.Rating,4)
str(Average.Rating)
```


```{r}
Final.Table <- cbind(united[,1:4], round(Average.Rating,0))
colnames(Final.Table) <- c("Player Name", "State", "Total Points", "Pre-Rating","Average Pre-Rating of Opponents")
head(Final.Table,4)
write.csv(Final.Table, file = "/Users/josemawyin/Library/Mobile Documents/com~apple~CloudDocs/Data Science Masters /607/Project1/Final_Table.csv")
```

